apiVersion: v1
kind: Pod
metadata:
  name: diego-nginx
  labels:
    app: diego-nginx
spec:
  containers:
    - name: container-pod-nginx
      image: nginx/lastest
      ports:
        - containerPort: 80


apiVersion: v1
kind: Pod
metadata:
  name: validador_cpf
  labels:
    app: validador_cpf
spec:
  containers:
    - name: validador_cpf
      image: odiegonicoletti/validador_cpf_java
      ports:
        - containerPort: 8300

# kubectl apply -f pod-nginx.yml
# kubectl describe -f pod-nginx.yml
# kubectl delete -f pod-nginx.yml
