- hosts: all
  tasks:
    #- name: "Criando um arquivo a toa no servidor"
      #shell: "echo 'escrevendo algo no servidor' >> teste.txt"
      #shell: "sudo apt install nginx -y"

    - name: "Roda: sudo apt update"
      become: yes
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #Um dia
    
    - name: "Instala pacotes em lote"
      apt:
        name: "{{ item }}"
        state: latest
      become: yes # roda com sudo
      with_items:
        - nginx